syncthing-password: ENC[AES256_GCM,data:JXZcXQ==,iv:nb2j74BsS8vfi0z0Uv4NLWlibVYBAGGCvTex3efEYFA=,tag:k2jyHV0A8eXeamojdQ6sag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdGkwdTVaK2plbGkrdVNN
            K3hsRGNTdjcxdjNIMVZxTHFpaktDR1JTSzN3CllNR3JUU01NZWx0czU2bXFBdnY4
            TFMzbk9tVmxaVTBwZUNUNVlUWE1KZGcKLS0tIDB2QVF1MW5lTCtlN3VXQlA4akpy
            NzEwUzJiVFJyZThtL0ZGOXE5a2kyRlEKodZaWgpOcLC6ETtje31vG8IG2gfQF7Ye
            jKbY+9OqYqfj9jLa44gbrBGWvZAL7511JB0X+kp7Y0Ra0MJQsclU0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19xkfsp5ykrjf860kvfp7880pe2d3kh888lglupq8pkm5pvupks4s6adar3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaE5ralZNL2tSeW1objR4
            RGZxL096VVRNdjlVWmlqa2hUNGtCMisvZVFjClNvNTJ1ZjlLelJjTTdMTEZKSWo0
            S0lyb3NPOFpLR3lIUmF0VkszZWJnSUEKLS0tIEtlQmdnN3B1ZWFHd2ZJd0d2RE5z
            VllHSURYamdxc1hBN3dkTzY3bzA4OUkKGN5N1qToO0k5kR91E2OhTv2lQw61/0b+
            KIShuwqeEim0BDSrSTzA/cNfO44QT3jeIPW5br3Sq4P+QQg5oWDANw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d0ay07mf03t2l7x75ytap26mhvqheu3eld5hvaqtqfha0yu72fdq8a7d5w
    lastmodified: "2026-06-09T18:45:58Z"
    mac: ENC[AES256_GCM,data:WgFtSmQaN5kBkwy4oyWra94xlUOl6KdZrfju0bUkZjh4uGLQ7O1QfMv7WxGbNy706yyc+iY0koN24XapcxgcNe447d6jdcaBx5Vj644e630j9iBHLtq8/qVcTZGYiqTqfLwastjlz4rcKTaj4UfyXtq6d2uwoPyXhd91M0cajbc=,iv:84xFdACoynrNGJUo/wlwEYJ8p5ZVCvhNqubKurtZSbk=,tag:kNCmYwtAKwUHaRbtIkihyA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
